Repository rgrmra/webserv, pull requests merged in 2025-03, with the labels that each got.

#102 adiciona webserv não bloqueante com múltiplos streams
  configurations/new.conf
  index.php
  index.py
  src/CGI/Cgi.cpp
  src/CGI/Cgi.hpp
  src/connection/AStream.cpp
  src/connection/AStream.hpp
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/connection/IStream.hpp
  src/connection/WebServ.cpp
  src/connection/WebServ.hpp
  src/file/AFile.cpp
  src/file/AFile.hpp
  src/file/AutoIndex.cpp
  src/file/AutoIndex.hpp
  src/file/Cgi.cpp
  src/file/Cgi.hpp
  src/file/Directory.cpp
  src/file/Directory.hpp
  src/file/File.cpp
  src/file/File.hpp
  src/file/Page.cpp
  src/file/Page.hpp
  src/file/Resource.cpp
  src/file/Resource.hpp
  src/file/Text.cpp
  src/file/Text.hpp
  src/main.cpp
  src/parser/Request.cpp
  src/response/code.hpp
  src/response/header.hpp
  src/response/process.cpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
  tests/CMakeLists.txt
  tests/request_test.cpp
  var/www/html/index.php
  var/www/html/index.py
  var/www/html/mysite/index.py
Labels: bug, enhancement

#103 Refactor/webserv
  src/connection/AStream.cpp
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/connection/WebServ.cpp
  src/file/Cgi.cpp
  src/file/Directory.cpp
  src/file/File.cpp
  src/file/Page.cpp
  src/file/Resource.cpp
  src/parser/request.cpp
  src/parser/request.hpp
  tests/request_test.cpp
  var/www/html/index.php
Labels: enhancement

#107 Melhorias na classe WebServ
  src/connection/AStream.cpp
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/connection/WebServ.cpp
  src/file/Cgi.cpp
  src/file/File.cpp
  src/response/process.cpp
  src/response/response.cpp
  var/www/html/index.py
  var/www/html/mysite/index.py
Labels: enhancement

#109 Validação da URI e outras implementações
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/connection/WebServ.cpp
  src/connection/WebServ.hpp
  src/file/Cgi.cpp
  src/file/Cgi.hpp
  src/file/Directory.cpp
  src/file/File.cpp
  src/file/Page.cpp
  src/parser/Location.cpp
  src/parser/Location.hpp
  src/parser/directive.cpp
  src/parser/request.cpp
  src/parser/request.hpp
  src/response/URL.cpp
  src/response/URL.hpp
  src/response/process.cpp
  src/response/process.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
  tests/request_test.cpp
  tests/status_test.cpp
  var/www/html/index.php
Labels: bug, enhancement

#112 Parser do Transfer-Encoding
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/parser/Http.cpp
  src/parser/request.cpp
  src/parser/request.hpp
  src/response/process.cpp
Labels: enhancement

#115 fix: request body timeout
  src/parser/request.cpp
Labels: bug

#122 Adiciona DAC
  src/response/URL.cpp
  src/response/URL.hpp
  src/response/process.cpp
  src/response/process.hpp
Labels: enhancement

#123 Add function to check if directory is empty
  src/response/URL.cpp
  src/response/URL.hpp
Labels: enhancement

#124 feat: add DAC deletable
  src/file/Cgi.cpp
  src/response/URL.cpp
  src/response/URL.hpp
Labels: enhancement

#126 Feature/cgi parser
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/file/Cgi.cpp
  src/file/Cgi.hpp
  src/response/URL.cpp
  src/response/header.hpp
  src/response/process.cpp
  src/response/response.cpp
  src/response/response.hpp
Labels: bug, enhancement

#127 Adiciona chamada do CGI no método POST
  src/connection/WebServ.cpp
  src/response/process.cpp
  src/response/response.cpp
Labels: bug, enhancement

#129 Implementacao do metodo DELETE
  Dockerfile
  docker-compose.yml
  scripts/entrypoint.sh
  src/response/code.hpp
  src/response/process.cpp
  src/response/process.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: enhancement

#130 Enhance tests and add tests for parser.cpp
  external/CMakeLists.txt
  src/response/code.hpp
  src/response/response.cpp
  src/response/status.hpp
  tests/CMakeCommon.cmake
  tests/CMakeLists.txt
  tests/README.md
  tests/afile_test.cpp
  tests/http/CMakeLists.txt
  tests/http/header_test.cpp
  tests/http/request_test.cpp
  tests/mime/CMakeLists.txt
  tests/mime/mime_test.cpp
  tests/mocks/CMakeLists.txt
  tests/mocks/MockParser.hpp
  tests/mocks/mock_connection.hpp
  tests/network/CMakeLists.txt
  tests/network/connection_test.cpp
  tests/parser/CMakeLists.txt
  tests/parser/config_parser_test.cpp
  tests/parser/parser_test.cpp
  tests/response/CMakeLists.txt
  tests/response/response_builder_test.cpp
  tests/text_test.cpp
  tests/utils/CMakeLists.txt
  tests/utils/code_test.cpp
  tests/utils/directive_test.cpp
  tests/utils/location_test.cpp
  tests/utils/status_test.cpp
  tests/utils/test_helpers.hpp
Labels: documentation, enhancement, tests

#131 Feature/return error pages
  src/connection/WebServ.cpp
  src/file/Cgi.cpp
  src/response/response.cpp
Labels: enhancement

#133 refact: add cgi header values
  src/file/Cgi.cpp
  var/www/html/404.html
  var/www/html/file
  var/www/html/file1
  var/www/html/file2
  var/www/html/upload.html
Labels: enhancement

#134 Adiciona tests para url.cpp
  tests/mocks/MockLocation.hpp
  tests/mocks/MockServer.hpp
  tests/mocks/mock_connection.hpp
  tests/response/url_simple_test.cpp
  tests/response/url_test.cpp
  tests/response/url_test_simple.cpp
Labels: enhancement, tests

#137 Arruma CGI Internal Server Error
  configurations/new.conf
  src/connection/Connection.cpp
  src/file/Cgi.cpp
  src/parser/request.cpp
  src/response/process.cpp
  src/response/process.hpp
  src/response/response.cpp
Labels: bug

#139 hotfix/correcao de bugs e reestruturacao de pasta
  src/response/URL.cpp
  src/response/methods/delete.cpp
  src/response/methods/get.cpp
  src/response/methods/post.cpp
  src/response/process.cpp
Labels: bug, enhancement

#140 136 path info path translated
  .vscode/settings.json
  configurations/default.conf
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/file/Resource.cpp
  src/main.cpp
  src/parser/directive.cpp
  src/parser/directive.hpp
  src/parser/request.cpp
  src/response/URL.cpp
  src/response/response.cpp
  tests/http/request_test.cpp
  tests/mocks/mock_connection.hpp
  tests/network/connection_test.cpp
  tests/response/url_simple_test.cpp
  tests/response/url_test.cpp
  tests/response/url_test_simple.cpp
Labels: enhancement

#146 Melhora a chamada de alguns métodos e na legibilidade
  src/parser/directive.cpp
  src/parser/parser.cpp
  src/parser/parser.hpp
  src/parser/request.cpp
  src/response/URL.cpp
  src/response/method.cpp
  src/response/method.hpp
  src/response/methods/delete.cpp
  src/response/methods/get.cpp
  src/response/process.cpp
  src/response/process.hpp
  src/response/response.cpp
Labels: enhancement

#148 refactor: remove system dependency and use remove
  src/response/methods/delete.cpp
Labels: enhancement

#150 Adiciona URL decoder no target e header value
  src/parser/request.cpp
  src/response/URL.cpp
  src/response/URL.hpp
Labels: bug, enhancement

#151 refactor: change and separate constants
  CMakeLists.txt
  compile_commands.json
  src/connection/AStream.cpp
  src/connection/Connection.cpp
  src/connection/WebServ.cpp
  src/connection/WebServ.hpp
  src/constant/code.hpp
  src/constant/env.hpp
  src/constant/header.hpp
  src/constant/method.cpp
  src/constant/method.hpp
  src/constant/size.hpp
  src/constant/standard.hpp
  src/constant/status.hpp
  src/file/Cgi.cpp
  src/file/Cgi.hpp
  src/parser/Http.cpp
  src/parser/directive.cpp
  src/parser/parser.cpp
  src/parser/parser.hpp
  src/parser/request.cpp
  src/response/response.cpp
  src/response/response.hpp
  tests/utils/directive_test.cpp
  tests/utils/location_test.cpp
Labels: enhancement

#152 fix: unbereable compile_comands.json
  Makefile
  compile_commands.json
  compile_flags.txt
Labels: enhancement
