Repository rgrmra/webserv, pull requests merged in 2025-02, with the labels that each got.

#14 feat: add webserv and connection
  CMakeLists.txt
  compile_commands.json
  configurations/new.conf
  configurations/teste.conf
  src/main.cpp
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Http.cpp
  src/parsers/Location.cpp
  src/parsers/Server.cpp
  src/parsers/WebServ.cpp
  src/parsers/WebServ.hpp
  src/parsers/directive.cpp
  src/parsers/parser.hpp
  src/response/code.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: enhancement

#17 Altera CI para evitar run duplo do workflow
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: enhancement

#20 feat: parse and add fastcgi directive
  configurations/default.conf
  src/parsers/Location.cpp
  src/parsers/Location.hpp
  src/parsers/directive.cpp
  src/parsers/directive.hpp
  src/parsers/parser.cpp
Labels: enhancement

#27 Feature/connection
  src/main.cpp
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/WebServ.cpp
  src/parsers/WebServ.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: bug, enhancement

#29 test: add tests to location
  tests/CMakeLists.txt
  tests/location_test.cpp
Labels: tests

#25 Request Parser
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Request.cpp
  src/parsers/Request.hpp
Labels: enhancement

#32 feat: add keep-alive connection
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/WebServ.cpp
Labels: enhancement

#33 fix: conditional jump
  src/parsers/Connection.cpp
Labels: bug

#22 Implementação dos testes unitários
  CMakeLists.txt
  Makefile
  Testing/Temporary/CTestCostData.txt
  Testing/Temporary/LastTest.log
  external/CMakeLists.txt
  src/parsers/directive.cpp
  src/parsers/directive.hpp
  src/parsers/parser.hpp
  tests/CMakeLists.txt
  tests/directive_test.cpp
  tests/parser_test.cpp
Labels: enhancement, tests

#38 Parsear request linha à linha
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Request.cpp
  src/parsers/Request.hpp
  src/parsers/WebServ.cpp
  src/parsers/parser.cpp
  src/response/code.hpp
  src/response/header.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: bug, enhancement

#41 fix: request parser bad request
  src/parsers/Connection.cpp
  src/parsers/Request.cpp
  src/parsers/WebServ.cpp
Labels: bug

#43 39 implementa testes para o request.cpp
  tests/CMakeLists.txt
  tests/request_test.cpp
Labels: tests

#48 refact: improve keep-alive connection
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/WebServ.cpp
  src/parsers/WebServ.hpp
Labels: bug, enhancement

#46 Feature/merge response
  configurations/php-test.conf
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/WebServ.cpp
  src/response/response.cpp
  src/response/response.hpp
  var/www/html/mysite/post/index.html
  var/www/html/mysite2/Depr-chopper-L-64.png
  var/www/html/mysite2/a.png
  var/www/html/mysite2/index.html
  var/www/html/mysite2/op.gif
Labels: enhancement

#50 44 Adiciona testes para a classe connection
  .vscode/settings.json
  tests/CMakeLists.txt
  tests/connection_test.cpp
Labels: tests

#51 refact: improve response
  compile_commands.json
  configurations/new.conf
  src/files/AFile.cpp
  src/files/AFile.hpp
  src/files/File.cpp
  src/files/File.hpp
  src/files/Page.cpp
  src/files/Page.hpp
  src/main.cpp
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Mime.cpp
  src/parsers/Mime.hpp
  src/parsers/Request.cpp
  src/parsers/WebServ.cpp
  src/parsers/WebServ.hpp
  src/parsers/mimes.json
  src/parsers/parser.cpp
  src/response/code.hpp
  src/response/header.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
  var/www/html/index.html
Labels: enhancement

#52 refact: change http of Connection from parameter
  CMakeLists.txt
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/WebServ.cpp
Labels: enhancement

#54 feat: add operator[] overload to get header
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/response/response.cpp
Labels: enhancement

#57 Implementa mais validacoes na parte da Request
  .github/workflows/build.yaml
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Request.cpp
  src/parsers/Request.hpp
  src/parsers/WebServ.cpp
  src/parsers/directive.cpp
  src/parsers/directive.hpp
  src/response/code.hpp
  src/response/header.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: enhancement

#59 Feature/response
  src/response/response.cpp
Labels: bug

#60 fix: test
  CMakeLists.txt
  tests/main.cpp
Labels: bug

#64 test: enhance request parsing tests with additional cases
  tests/request_test.cpp
Labels: tests

#68 Fix CI trigger
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: bug

#69 Feature/response
  src/main.cpp
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Server.hpp
  src/parsers/WebServ.cpp
  src/parsers/WebServ.hpp
  src/response/code.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: enhancement

#71 Test pr
  .github/workflows/test.yaml
Labels: bug

#72 Melhorias na Response
  src/files/Page.cpp
  src/files/Text.cpp
  src/files/Text.hpp
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/directive.cpp
  src/response/code.hpp
  src/response/header.hpp
  src/response/process.cpp
  src/response/process.hpp
  src/response/response.cpp
  src/response/response.hpp
  src/response/status.hpp
Labels: bug, enhancement

#74 fix: accept only requests with CRLF
  src/parsers/Connection.cpp
  src/parsers/Request.cpp
  src/response/URL.cpp
  src/response/URL.hpp
  tests/request_test.cpp
Labels: bug

#75 refact: apply correct identation and simplify logic
  src/parsers/directive.cpp
  src/parsers/directive.hpp
  src/parsers/parser.hpp
  tests/directive_test.cpp
Labels: bug, enhancement

#77 76 Implementa testes para o arquivo AFile.cpp
  tests/CMakeLists.txt
  tests/Common.hpp
  tests/afile_test.cpp
  tests/connection_test.cpp
  tests/main.cpp
Labels: tests

#79 78 Add tests for Mime.cpp
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  tests/CMakeLists.txt
  tests/connection_test.cpp
  tests/mime_test.cpp
  tests/request_test.cpp
Labels: enhancement, tests

#91 89 Implementa tests para header.hpp
  tests/CMakeLists.txt
  tests/header_test.cpp
Labels: tests

#92 Adiciona templata para criação de issue
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: enhancement

#93 35 implementar cgi
  Makefile
  src/CGI/Cgi.cpp
  src/CGI/Cgi.hpp
  src/parsers/Connection.cpp
  src/parsers/Connection.hpp
  src/parsers/Request.cpp
  src/parsers/Request.hpp
  src/response/process.cpp
  tests/request_test.cpp
Labels: enhancement

#96 Implementa testes para status.hpp
  tests/CMakeLists.txt
  tests/status_test.cpp
Labels: tests

#99 Adiciona testes para o text.cpp
  tests/CMakeLists.txt
  tests/text_test.cpp
Labels: tests

#101 Refactor/webserv
  CMakeLists.txt
  compile_commands.json
  src/connection/Connection.cpp
  src/connection/Connection.hpp
  src/connection/WebServ.cpp
  src/connection/WebServ.hpp
  src/file/AFile.cpp
  src/file/AFile.hpp
  src/file/AutoIndex.cpp
  src/file/AutoIndex.hpp
  src/file/File.cpp
  src/file/File.hpp
  src/file/Page.cpp
  src/file/Page.hpp
  src/file/Text.cpp
  src/file/Text.hpp
  src/main.cpp
  src/parser/Http.cpp
  src/parser/Http.hpp
  src/parser/Location.cpp
  src/parser/Location.hpp
  src/parser/Mime.cpp
  src/parser/Mime.hpp
  src/parser/Request.cpp
  src/parser/Request.hpp
  src/parser/Server.cpp
  src/parser/Server.hpp
  src/parser/directive.cpp
  src/parser/directive.hpp
  src/parser/mimes.json
  src/parser/parser.cpp
  src/parser/parser.hpp
  src/response/response.cpp
  src/service/logger/logger.cpp
  src/service/logger/logger.hpp
  src/util/color/color.cpp
  src/util/color/color.hpp
  tests/afile_test.cpp
  tests/directive_test.cpp
  tests/mime_test.cpp
  tests/request_test.cpp
Labels: bug, enhancement
