Repository rgrmra/webserv, pull requests merged in 2025-05, with the labels that each got.

#157 Feature/refactor
  CMakeLists.txt
  compile_flags.txt
  configurations/new.conf
  src/connection/AStream.cpp
  src/connection/AStream.hpp
  src/connection/Connection.cpp
  src/connection/IStream.hpp
  src/connection/WebServ.cpp
  src/constant/code.hpp
  src/constant/status.hpp
  src/constant/step.hpp
  src/file/Cgi.cpp
  src/file/Directory.cpp
  src/file/File.cpp
  src/file/Page.cpp
  src/file/Text.cpp
  src/main.cpp
  src/parser/configuration/Http.cpp
  src/parser/configuration/Http.hpp
  src/parser/configuration/Location.cpp
  src/parser/configuration/Location.hpp
  src/parser/configuration/Server.cpp
  src/parser/configuration/Server.hpp
  src/parser/mime/Mime.cpp
  src/parser/mime/Mime.hpp
  src/parser/mime/mimes.json
  src/parser/request/request.cpp
  src/parser/request/request.hpp
  src/response/URL.cpp
  src/response/URL.hpp
  src/response/response.cpp
  src/response/response.hpp
  tests/CMakeLists.txt
  tests/http/request_test.cpp
  tests/mocks/MockParser.hpp
  tests/parser/config_parser_test.cpp
  tests/utils/test_helpers.hpp
Labels: enhancement

#158 refactor: project structure
  configurations/new.conf
  index.php
  index.py
  src/connection/AStream.cpp
  src/connection/Connection.hpp
  src/constant/code.hpp
  src/constant/size.hpp
  src/constant/standard.hpp
  src/file/Cgi.cpp
  src/parser/configuration/Location.cpp
  src/parser/configuration/Location.hpp
  src/parser/directive.cpp
  src/parser/directive.hpp
  src/parser/mime/Mime.cpp
  src/parser/parser.cpp
  src/parser/request/request.cpp
  src/parser/request/request.hpp
  src/response/URL.cpp
  src/response/methods/delete.cpp
  src/response/methods/multipart.cpp.bak
  src/response/methods/post.cpp
  src/response/methods/upload.cpp.bak
  src/response/process.cpp
  src/response/process.hpp
  var/www/html/index.php
  var/www/html/mysite/cgi/post/index.php
  var/www/html/mysite/formulario/index.html
Labels: bug, enhancement

#162 reafctor: cgi and add post files
  src/connection/WebServ.cpp
  src/constant/code.hpp
  src/constant/standard.hpp
  src/constant/status.hpp
  src/file/Cgi.cpp
  src/parser/mime/Mime.cpp
  src/response/URL.cpp
  src/response/methods/post.cpp
  src/response/process.cpp
  tests/mime/mime_test.cpp
Labels: bug

#163 Refactor WebServ
  configurations/new.conf
  src/connection/AStream.cpp
  src/connection/AStream.hpp
  src/connection/Connection.cpp
  src/connection/IStream.hpp
  src/connection/WebServ.cpp
  src/connection/WebServ.hpp
  src/file/Cgi.cpp
  src/file/Cgi.hpp
  src/parser/directive.cpp
  src/parser/parser.cpp
  src/parser/parser.hpp
  src/response/URL.cpp
  src/response/URL.hpp
  src/response/process.cpp
  src/response/response.cpp
  src/response/response.hpp
  tests/utils/directive_test.cpp
Labels: bug, enhancement

#166 Refactor
  src/parser/directive.cpp
  src/response/URL.cpp
  tests/utils/directive_test.cpp
Labels: bug

#167 Fix DELETE method logic and clean up whitespace
  src/connection/AStream.cpp
  src/connection/WebServ.cpp
  src/response/methods/delete.cpp
  var/www/html/404.html
  var/www/html/file
  var/www/html/file1
  var/www/html/file2
Labels: bug

#168 refactor: improvements
  configurations/default.conf
  configurations/new.conf
  src/constant/standard.hpp
  src/parser/configuration/Http.cpp
  src/parser/configuration/Http.hpp
  src/parser/configuration/Location.cpp
  src/parser/configuration/Location.hpp
  src/parser/configuration/Server.cpp
  src/parser/configuration/Server.hpp
  src/parser/directive.cpp
  src/parser/directive.hpp
  src/parser/parser.cpp
  tests/utils/directive_test.cpp
Labels: enhancement

#169 refactor: test
  configurations/default.conf
Labels: bug

#175 0bvim patch 1 readme
  README.MD
Labels: documentation

#177 Improve pages and fix some bugs
  Makefile
  configurations/default.conf
  scripts/configuration.json
  scripts/webserv_tester.py
  src/connection/WebServ.cpp
  src/connection/WebServ.hpp
  src/constant/standard.hpp
  src/file/Cgi.cpp
  src/parser/directive.cpp
  var/www/html/404.html
  var/www/html/cgi/cgi_test.php
  var/www/html/cgi/cookies.php
  var/www/html/cgi/form_handler.php
  var/www/html/cgi/index.html
  var/www/html/cgi/library/css/layout.css
  var/www/html/cgi/php/cgi_test.php
  var/www/html/cgi/php/cookies.php
  var/www/html/cgi/php/delete_files.php
  var/www/html/cgi/php/form_handler.php
  var/www/html/cgi/php/index.php
  var/www/html/cgi/php/info.php
  var/www/html/cgi/php/upload_handler.php
  var/www/html/cgi/python/directory.py
  var/www/html/cgi/python/index.py
  var/www/html/cgi/python/tic_tac_toe.py
  var/www/html/cgi/tic_tac_toe.py
  var/www/html/cgi/upload_handler.php
  var/www/html/cgi/upload_handler.sh
  var/www/html/deletable/ft_transcendence.pdf
  var/www/html/deletable/giphy.gif
  var/www/html/directory/sub_directory/sub_directory_file.txt
  var/www/html/directory/sub_directory/sub_sub_directory/sub_sub_directory.txt
  var/www/html/directory/sub_directory/sub_sub_directory_off/sub_sub_directory_off.txt
  var/www/html/directory/sub_directory_off/sub_directory_off_file.txt
  var/www/html/directory/sub_directory_off/sub_sub_directory/sub_off_sub_directory_file.txt
  var/www/html/directory/subdirectory/subdirectory_file.txt
  var/www/html/error_pages/404.html
  var/www/html/error_pages/500.html
  var/www/html/error_pages/504.html
  var/www/html/method/delete/.gitkeep
  var/www/html/method/get/.gitkeep
  var/www/html/method/limit/10b/.gitkeep
  var/www/html/method/limit/1b/.gitkeep
  var/www/html/method/limit/5b/.gitkeep
  var/www/html/method/post/.gitkeep
  var/www/html/static_site/index.html
  var/www/html/static_site/library/css/layout.css
  var/www/html/uploads/.gitkeep
Labels: bug, enhancement

#178 Adiciona documentação
  scripts/configuration.json
  src/connection/Connection.cpp
  src/connection/WebServ.cpp
  src/constant/code.hpp
  src/constant/status.hpp
  src/file/Page.cpp
  src/parser/request/request.cpp
  src/response/response.cpp
  var/www/html/cgi/index.html
  var/www/html/cgi/library/css/layout.css
  var/www/html/cgi/php/infinit.php
  var/www/html/cgi/python/infinit.py
  var/www/html/documentation/index.html
Labels: enhancement

#180 fix: deprecated cgi in tic tac toe
  var/www/html/cgi/python/tic_tac_toe.py
Labels: bug
